apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clara-bornan
  labels:
    app.kubernetes.io/name: clara-bornan
    app.kubernetes.io/part-of: clara-bornan-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clara-bornan
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85