apiVersion: v1
kind: ConfigMap
metadata:
  name: clara-bornan-config
  namespace: client-saas
data:
  NODE_ENV: "production"
  DEFAULT_LOCALE: "pt-BR"
  REDIS_URL: "redis://redis.shared.svc.cluster.local:6379"
  INSTALLATION_NAME: "Bornan Chat"
  INSTALLATION_PRICING_PLAN: "enterprise"
  INSTALLATION_PRICING_PLAN_QUANTITY: "9999"
  FRONTEND_URL: "https://chat.bornan.com.br"
  FORCE_SSL: "false"
  ENABLE_ACCOUNT_SIGNUP: "false"
  RAILS_LOG_TO_STDOUT: "true"
  LOG_LEVEL: "debug"
  LOG_SIZE: "500"
  RAILS_MAX_THREADS: "5"
  PGSSLMODE: "require"
