apiVersion: v1
kind: ConfigMap
metadata:
  name: clara-bornan-config
  namespace: client-saas
data:
  DEFAULT_LOCALE: "pt-BR"
  NODE_ENV: "production"
  INSTALLATION_NAME: "Bornan Chat"
  FRONTEND_URL: "https://chat.bornan.com.br"
  FORCE_SSL: "false"
  DISABLE_ENTERPRISE: "true"
  ENABLE_ACCOUNT_SIGNUP: "true"
  REDIS_URL: "redis://redis.shared.svc.cluster.local:6379"
  POSTGRES_DATABASE: "saas-chatbornan"
  RAILS_ENV: "production"
  RAILS_MAX_THREADS: "5"
  MAILER_SENDER_EMAIL: bornan <accounts@bornan.com>
  #SMTP_HOST: "smtp.office365.com"
  SMTP_DOMAIN: "smtp.office365.com"
  SMTP_ADDRESS: "noreply@bornan.com.br"
  SMTP_PORT: "587"
  SMTP_ENABLE_STARTTLS_AUTO: "true"
  SMTP_USE_SSL: "false"
  # plain,login,cram_md5
  SMTP_AUTHENTICATION: "login"
  # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
  SMTP_OPENSSL_VERIFY_MODE: "none"
  ACTIVE_STORAGE_SERVICE: "local"
  RAILS_LOG_TO_STDOUT: "true"
  LOG_LEVEL: "debug"
  LOG_SIZE: "500"
  ENABLE_PUSH_RELAY_SERVER: "true"
