apiVersion: apps/v1
kind: Deployment
metadata:
  name: clara-bornan
  namespace: client-saas
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: clara-bornan
  template:
    metadata:
      labels:
        app: clara-bornan
    spec:
      containers:
        - name: clara-bornan
          image: bornan.azurecr.io/clara-bornan:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "docker/entrypoints/rails.sh"]
          args: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: clara-bornan-config
            - secretRef:
                name: clara-bornan-secrets
          env:
            - name: RAILS_ENV
              value: "production"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
