apiVersion: v1
kind: Secret
metadata:
  name: clara-bornan-secrets
  namespace: client-saas
type: Opaque
stringData:
  SECRET_KEY_BASE: "27086a984a3d3e0063604573a47578a1c5c1703b0f518982da3718bd93c8a9bc22ca8d755906ddc168d4cf3f133"
  # DB/Redis externos — use URLs completas
  POSTGRES_HOST: "bornan-db.postgres.database.azure.com"
  POSTGRES_DATABASE: "saas-chatbornan"
  POSTGRES_USERNAME: "bornan"
  POSTGRES_PASSWORD: "0GWMe522u26fNhJ"
  REDIS_URL: "redis://redis.shared.svc.cluster.local:6379"

  # SMTP Office 365 (exemplo)
  SMTP_DOMAIN: "smtp.office365.com"
  SMTP_ADDRESS: "noreply@bornan.com.br"
  SMTP_PORT: "587"
  SMTP_ENABLE_STARTTLS_AUTO: "true"
  SMTP_USE_SSL: "false"
  SMTP_USERNAME: "bruno@bornan.com.br"
  SMTP_PASSWORD: "vdvzlnjmhnxjrsth"
  SMTP_AUTHENTICATION: "login"
  SMTP_OPENSSL_VERIFY_MODE: "none"

  # Sender (from)
  MAILER_SENDER_EMAIL: "bornan <accounts@bornan.com.br>"

  IOS_APP_ID: "L7YLMN4634.com.clara-bornan.app"
  ANDROID_BUNDLE_ID: "com.clara-bornan.app"
  ANDROID_SHA256_CERT_FINGERPRINT: "AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8"

  ACTIVE_STORAGE_SERVICE: "local"
